version: '3.3'

volumes:
    pg_data:
    static:
    media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: apicqq/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: apicqq/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: apicqq/foodgram_gateway:latest
    depends_on:
      - backend
      - db
    ports:
      - "8000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/media/
