# Generated by Django 3.2 on 2023-11-21 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления должно быть не менее 1 минуты.'), django.core.validators.MaxValueValidator(32767, 'Время приготовления должно быть не более 32767 минут.')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов должно быть не менее 1.'), django.core.validators.MaxValueValidator(10000, 'Количество ингредиентов должно быть не более 10000.')], verbose_name='Количество ингредиентов'),
        ),
    ]
